version: "3"
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    networks:
      - "ci"
networks:
  ci:
    external:
      name: cloudbuild
